name: A5a – Replicación de la falla
description: Template para levantar el issue de replicación de la falla (usar MR-[ID])
title: "A5a – Replicación de la falla [MR-ID]"
labels: ["mantenimiento", "Pendiente-Validación"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Objetivo
        Garantizar que el responsable técnico tenga acceso autorizado al sistema, entorno o documentación necesaria para replicar la falla o validar la propuesta, dejando evidencia en plantillas y en el Registro de MR-[ID].

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist de pasos (Mantenedor)
      options:
        - label: Revisar Sección 1 del Registro de MR-[ID]
        - label: Descargar el repositorio desde GitHub
        - label: Instalar el sistema en entorno local siguiendo README.md / INSTALL.md
        - label: Documentar instalación en la plantilla Evidencia de instalación
        - label: Replicar la falla siguiendo la descripción del MR
        - label: Documentar acciones y resultados en la plantilla Replicación de falla
        - label: Capturar evidencia (logs, capturas, mensajes de error)
        - label: Cambiar estatus del issue a Pendiente-Validación
        - label: Actualizar Registro de MR-[ID] y Historial
        - label: Notificar en este issue que la documentación fue actualizada

  - type: textarea
    id: evidencia_instalacion
    attributes:
      label: Evidencia de instalación
      description: Subir archivo o enlace con la plantilla de instalación

  - type: textarea
    id: replicacion_falla
    attributes:
      label: Replicación de la falla
      description: Subir archivo o enlace con la plantilla de replicación

  - type: textarea
    id: comentario_final
    attributes:
      label: Comentario final (Mantenedor)
      description: "Al concluir, dejar un comentario con el formato: 'Actividad A5a completada. Solicito revisión del LP.'"
