name: A5b – Validación de sugerencia de mejora
description: Template para levantar el issue de validación de una sugerencia (usar MR-[ID])
title: "A5b – Validación de sugerencia [MR-ID]"
labels: ["mantenimiento", "Pendiente-Validación"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Objetivo
        Garantizar que el responsable técnico valide la viabilidad y no duplicidad de la sugerencia de mejora, dejando evidencia clara y trazable.

  - type: input
    id: mr_id
    attributes:
      label: MR-ID
      description: Identificador del mantenimiento (ej. MR-1234)
      placeholder: MR-XXXX

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist de pasos (Mantenedor)
      options:
        - label: Revisar Sección 1 del Registro de MR-[ID] (descripción y contexto)
        - label: Descargar el repositorio desde GitHub
        - label: Instalar y ejecutar el sistema en entorno local; documentar en plantilla de instalación
        - label: Revisar rutas/servicios/módulos para detectar implementaciones similares
        - label: Documentar hallazgos en la plantilla "Validación de sugerencia del mantenimiento"
        - label: Adjuntar la plantilla como comentario en este issue
        - label: Cambiar estatus a Pendiente-Validación y notificar al LP

  - type: textarea
    id: resumen_sugerencia
    attributes:
      label: Resumen de la sugerencia
      description: Copiar la descripción de la Sección 1 del Registro de MR-[ID]
