name: "a6-identificacion"
description: "Sub-issue para que el Mantenedor documente el mapa de referencias de archivos/módulos (MR-[ID])"
title: "A5a - Mapa de referencias [MR-ID]"
labels: ["mantenimiento", "Pendiente-Validación"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Objetivo
        Documentar el mapa de referencias de archivos y módulos relacionados con el mantenimiento **MR-[ID]**, incluyendo archivo principal, dependencias, cantidad de módulos impactados y observaciones.  
        La evidencia debe registrarse en la plantilla:  
        **Mapa de referencias de archivos/módulos para el mantenimiento – [ID]**

  - type: input
    id: mr_id
    attributes:
      label: MR-ID
      placeholder: "MR-XXXX"

      - type: textarea
    id: archivos_principales
    attributes:
      label: 📌 Archivos principales identificados
      description: Lista breve de los archivos directamente relacionados con la falla o mejora.
      placeholder: |
        Ejemplo:
        - /src/controllers/UserController.php
        - /src/services/NotificationService.js

        - type: textarea
    id: observaciones
    attributes:
      label: 📝 Observaciones relevantes
      description: Nota breve sobre impacto, complejidad o particularidades encontradas.
      placeholder: |
        Ejemplo:
        - Existe dependencia circular potencial con NotificationService.
        - UserController impacta flujos críticos de autenticación.
