name: "a6 - prioridad-sub"
description: "Sub-issue para documentar la asignación de prioridad (MR-[ID])"
title: "a6-prioridad-sub"
labels: ["mantenimiento", "prioridad"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Objetivo
        Asignar prioridad al mantenimiento según impacto y guía de priorización.  
        La evidencia debe registrarse en la plantilla:  
        **Asignación de prioridad – MR-[ID]**

  - type: input
    id: mr_id
    attributes:
      label: MR-ID
      description: Identificador del mantenimiento (ej. MR-1234)
      placeholder: MR-XXXX
