name: A6 – Asignación de prioridad
description: Issue principal para coordinar la asignación de prioridad de mantenimiento (MR-[ID])
title: "A6 – Asignación de prioridad [MR-ID]"
labels: ["mantenimiento", "Pendiente-Validación"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🎯 Objetivo
        Coordinar la asignación de prioridad del mantenimiento, incluyendo identificación de archivos, asignación de prioridad y validación informal.

  - type: input
    id: mr_id
    attributes:
      label: MR-ID
      description: Identificador del mantenimiento
      placeholder: MR-XXXX

  
