name: PHP Code Sniffer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      # PHP Code Sniffer Step
      - name: Run PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          version: latest # Use the latest version of PHPCS
          php_version: 8.1 # Match your PHP version
          path: ./ # Check the root directory
          standard: PSR12 # Use PSR12 coding standard
          ignore: vendor/,node_modules/ # Ignore unnecessary directories
          report: summary # Display a summary in the output
          report_file: phpcs-report.txt # Save report to a file
          extensions: php # Only check PHP files
          encoding: utf-8 # Default encoding for PHP files
          ignore_warnings_on_exit: true # Exit successfully despite warnings
